In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from chunk_utils import get_xpos_from_delays

In [2]:
data_dir = './/data//'
matplotlib.rcParams['figure.figsize'] = 24,15

In [3]:
df = pd.read_csv(data_dir+'cmu_dataset.csv')
df.head()

,subject,sessionIndex,rep,H.period,DD.period.t,UD.period.t,H.t,DD.t.i,UD.t.i,H.i,...,H.a,DD.a.n,UD.a.n,H.n,DD.n.l,UD.n.l,H.l,DD.l.Return,UD.l.Return,H.Return
0,s002,1,1,0.1491,0.3979,0.2488,0.1069,0.1674,0.0605,0.1169,...,0.1349,0.1484,0.0135,0.0932,0.3515,0.2583,0.1338,0.3509,0.2171,0.0742
1,s002,1,2,0.1111,0.3451,0.2340,0.0694,0.1283,0.0589,0.0908,...,0.1412,0.2558,0.1146,0.1146,0.2642,0.1496,0.0839,0.2756,0.1917,0.0747
2,s002,1,3,0.1328,0.2072,0.0744,0.0731,0.1291,0.0560,0.0821,...,0.1621,0.2332,0.0711,0.1172,0.2705,0.1533,0.1085,0.2847,0.1762,0.0945
3,s002,1,4,0.1291,0.2515,0.1224,0.1059,0.2495,0.1436,0.1040,...,0.1457,0.1629,0.0172,0.0866,0.2341,0.1475,0.0845,0.3232,0.2387,0.0813
4,s002,1,5,0.1249,0.2317,0.1068,0.0895,0.1676,0.0781,0.0903,...,0.1312,0.1582,0.0270,0.0884,0.2517,0.1633,0.0903,0.2517,0.1614,0.0818

In [4]:
u_indx = 1233
delays = np.array(df.iloc[:u_indx+32,3:])
username = df.iloc[u_indx,0]
typedname = '.tie5Roanl'

In [5]:
username

's005'

In [6]:
ypos = 0.01
ydelta = 0.0317

for dd in delays:
    xposvector = get_xpos_from_delays(dd, space_min = 0.006, max_delta_spacing=0.08)
    for char, xpos in zip(typedname, xposvector):
        plt.text(xpos, ypos + ydelta, char, fontsize=22)
    ypos += ydelta
plt.tight_layout()
plt.savefig(".//images//cmu//spatial_plot_" + username + ".svg", format='svg')
plt.close()